on:
  pull_request:
    types: [review_requested]
name: Notify review_requested on Slack
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: sandbox
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://fontawesome.com/icons/code-pull-request-draft?s=solid&f=classic
        SLACK_ICON_EMOJI: ':bell:'
        SLACK_MESSAGE: 'Your code review is expected :bell:'
        SLACK_TITLE: Code Review
        SLACK_LINK_NAMES: true
